config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/esis/Imalys:
      branch: main
      repo: https://codebase.helmholtz.cloud/esis/Imalys
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/esis/Imalys git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-mauve-chow.sh
        container: qc.acc_snazzy-purple-cattle
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/esis/Imalys find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-myrtle-deer.sh
        container: qc.doc_homely-flax-vole
      codebase.helmholtz.cloud/esis/Imalys git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-aquamarine-salamander.sh
        container: qc.doc_stinky-sangria-chimpanzee
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/esis/Imalys licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-celadon-starfish.sh
        container: qc.lic_tacky-cream-hare
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/esis/Imalys get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-coral-robin.sh
        container: qc.ver_shaky-razzmatazz-spitz
timeout: 5400
