config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/esis/Imalys:
      branch: main
      repo: https://codebase.helmholtz.cloud/esis/Imalys
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/esis/Imalys git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-champagne-cockroach.sh
        container: qc.acc_freaky-plum-ray
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/esis/Imalys find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-tomato-salamander.sh
        container: qc.doc_ready-coral-mouse
      codebase.helmholtz.cloud/esis/Imalys git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-denim-walrus.sh
        container: qc.doc_flabby-harlequin-havanese
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/esis/Imalys licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ecru-urchin.sh
        container: qc.lic_shabby-peach-olm
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/esis/Imalys get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-azure-sparrow.sh
        container: qc.ver_chummy-amaranth-dingo
timeout: 5400
