config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/esis/Imalys:
      branch: main
      repo: https://codebase.helmholtz.cloud/esis/Imalys
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/esis/Imalys git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-taupe-termite.sh
        container: qc.acc_craggy-saffron-paradise
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/esis/Imalys find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-puce-maltese.sh
        container: qc.doc_skimpy-beige-budgerigar
      codebase.helmholtz.cloud/esis/Imalys git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-ochre-hyena.sh
        container: qc.doc_chewy-yellow-dunker
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/esis/Imalys licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-razzmatazz-kudu.sh
        container: qc.lic_shaggy-buff-tarsier
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/esis/Imalys get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-celadon-flamingo.sh
        container: qc.ver_slimy-platinum-zebra
timeout: 5400
